package:
  name: pyfftw
  version: "0.12.0"

source:
 - url: https://files.pythonhosted.org/packages/4b/38/6f9539d274d02fbc3262e2f9a0c9dbac9b53393b3ed935612993f8df54bf/pyFFTW-0.12.0.tar.gz
   md5: 3bfaeb2fe270a6b9d290e8c24718326f
   fn: pyFFTW-0.12.0.tar.gz
   
 - url: http://www.fftw.org/fftw-3.3.6-pl2.tar.gz
   fn: fftw-3.3.6-pl2.tar.gz
   folder : fftw-src
 
build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysndfile = pysndfile:main
    #
    # Would create an entry point called pysndfile that calls pysndfile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 3

requirements:
  build:
    - python 
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - cython
    - nomkl
    
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - cython
    - nomkl
    
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}

test:
  # Python imports, check whether import works
  imports:
    - pyfftw

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose


about:
  home: https://pypi.python.org/pypi/pyFFTW, http://http://www.fftw.org
  license: GNU General Public License (GPL)
  summary: 'pyfftw provides an interface to fftw3 the'
  license_family: GPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
