package:
   name: easdif
   version: 1.4.26

build:
   number: 0

requirements:
   build:
      - python
      - numpy {{ numpy }}.*
      - cython
      - swig
      - cmake

   run:
      - python
      - numpy {{ numpy }}.*

test:
  # Python imports
  imports:
    - eaSDIF

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://sourceforge.net/projects/sdif/files/Easdif/
  license: LGPL

