package:
   name: easdif
   # please take car that this vesion matches the version of the underlying EASDIF
   # that is specified using the commit revision argument under source
   version: 1.4.30

source:
  svn_url: svn://svn.code.sf.net/p/sdif/code/trunk/Easdif
  svn_rev: 1872
  folder: EASDIF_SDIF
  
build:
   number: 2

requirements:
   build:
      - python {{ python }}
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - setuptools
      - cython
      - swig
      - cmake
      - numpy {{ numpy }}

   host:
      - python {{ python }}
      - numpy {{ numpy }}
   
   run:
      - python {{ python }}
      - {{ pin_compatible('numpy') }}

test:
  # Python imports
  imports:
    - eaSDIF

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://sourceforge.net/projects/sdif/files/Easdif/
  license: LGPL

