package:
   name: easdif
   version: 1.4.25

build:
   number: 2

requirements:
   build:
      - python
      - numpy x.x
      - cython
      - swig
      - cmake

   run:
      - python
      - numpy x.x

about:
  home: https://sourceforge.net/projects/sdif/files/Easdif/
  license: LGPL

