package:
  name: pysndfile
  version: "0.2.13"

source:
   - url: https://pypi.python.org/packages/04/0f/194319d4dcee6b4b52ba3809894764395b8f1f7e52d948dfe39712d8ded5/pysndfile-0.2.13.tar.gz
     fn: pysndfile-0.2.13.tar.gz
     md5: 6142ef7174d5af7e0b14057b031969ce
     
   - url: http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
     fn: libsndfile-1.0.28.tar.gz
     folder: libsndfile-src
     patches:
        - common.c.patch
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysndfile = pysndfile:main
    #
    # Would create an entry point called pysndfile that calls pysndfile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy  >=1.12.0
    
  run:
    - python
    - numpy  >=1.12.0

test:
  # Python imports
  imports:
    - pysndfile

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://forge.ircam.fr/p/pysndfile
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'pysndfile provides PySndfile, a Cython wrapper class for reading/writing soundfiles using libsndfile'
  license_family: LGPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
