package:
  name: as_pysrc
  version: "git_master"


build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - future
    - setuptools
    - cython
    - numpy 1.12*
    
  run:
    - python
    - numpy 1.12*

about:
  home: http://forge.ircam.fr/p/as_pysrc
  license: IRCAM internal use only
  summary: 'signal processing toolbox of analysis/synthesis team'
  license_family: PROPRIETARY

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
