{% set name = "py_find_1st" %}
{% set version = "1.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/51/94/d29e43472aa4dde37f91b3e1fcdf5f48b722285e54773acd688417184110/{{ name }}-{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: f99207bc83df361c4cd9c6c2aaf504907ffce7fdd33ae3d3cbf39c68a4f1c1a9

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysndfile = pysndfile:main
    #
    # Would create an entry point called pysndfile that calls pysndfile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - numpy {{ numpy }}
    - future
    - setuptools

  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
   
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}

test:
  # Python imports
  imports:
    - utils_find_1st.find_1st  

  files:
    - test
    
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cd test; python test_find_1st.py

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://forge.ircam.fr/p/pysndfile
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'pysndfile provides PySndfile, a Cython wrapper class for reading/writing soundfiles using libsndfile'
  license_family: LGPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
